name: 'Configure Private Repos'
description: 'Configure Git and Go for private repository access'
inputs:
  github_token:
    description: 'GitHub token for private repository access'
    required: true
  goprivate:
    description: 'Comma-separated list of module path prefixes for GOPRIVATE'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Configure Git for private repos
      shell: bash
      run: |
        git config --global url."https://x-access-token:${{ inputs.github_token }}@github.com/".insteadOf "https://github.com/"
        
    - name: Configure Go private modules
      if: ${{ inputs.goprivate != '' }}
      shell: bash
      run: |
        echo "GOPRIVATE=${{ inputs.goprivate }}" >> $GITHUB_ENV