name: 'Setup Node.js Environment'
description: 'Setup Node.js with mise and package manager (npm, yarn, pnpm, or bun) and install dependencies'
branding:
  icon: 'package'
  color: 'green'
inputs:
  node_version:
    description: 'Node.js version to install'
    required: false
    default: '22'
  package_manager:
    description: 'Package manager to use (npm, yarn, pnpm, or bun)'
    required: false
    default: 'npm'
  yarn_version:
    description: 'Yarn version to install'
    required: false
    default: 'latest'
  pnpm_version:
    description: 'PNPM version to install'
    required: false
    default: 'latest'
  bun_version:
    description: 'Bun version to install'
    required: false
    default: 'latest'
  install_deps:
    description: 'Install dependencies after setup'
    required: false
    default: 'true'
  working_directory:
    description: 'Working directory for package operations'
    required: false
    default: '.'
  cache_dependencies:
    description: 'Cache dependencies'
    required: false
    default: 'true'
  autoinit_env:
    description: 'Run env:init:ci script after installing dependencies'
    required: false
    default: 'false'
  allow_lockfile_modifications:
    description: 'Allow package managers to create or modify lockfiles'
    required: false
    default: 'true'

outputs:
  pm:
    description: 'Package manager command'
    value: ${{ steps.set-pm.outputs.pm }}
  pm_run:
    description: 'Package manager run command'
    value: ${{ steps.set-pm.outputs.pm_run }}
  cache_hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Install mise
      uses: jdx/mise-action@v2
    
    - name: Setup Node.js with mise
      shell: bash
      run: |
        mise use --global node@${{ inputs.node_version }}
        mise install
    
    - name: Set package manager variables
      id: set-pm
      shell: bash
      run: |
        case "${{ inputs.package_manager }}" in
          bun)
            echo "pm=bun" >> $GITHUB_OUTPUT
            echo "pm_run=bun run" >> $GITHUB_OUTPUT
            ;;
          yarn)
            echo "pm=yarn" >> $GITHUB_OUTPUT
            echo "pm_run=yarn run" >> $GITHUB_OUTPUT
            ;;
          pnpm)
            echo "pm=pnpm" >> $GITHUB_OUTPUT
            echo "pm_run=pnpm run" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "pm=npm" >> $GITHUB_OUTPUT
            echo "pm_run=npm run" >> $GITHUB_OUTPUT
            ;;
        esac
    
    - name: Install all package managers with mise
      shell: bash
      run: |
        mise use --global yarn@${{ inputs.yarn_version }}
        mise use --global pnpm@${{ inputs.pnpm_version }}
        mise use --global bun@${{ inputs.bun_version }}
        mise install
    
    - name: Verify package manager installation
      shell: bash
      run: |
        echo "Verifying ${{ inputs.package_manager }} installation..."
        case "${{ inputs.package_manager }}" in
          bun)
            bun --version || { echo "Error: Bun not found in PATH"; exit 1; }
            ;;
          yarn)
            yarn --version || { echo "Error: Yarn not found in PATH"; exit 1; }
            ;;
          pnpm)
            pnpm --version || { echo "Error: PNPM not found in PATH"; exit 1; }
            ;;
          npm)
            npm --version || { echo "Error: NPM not found in PATH"; exit 1; }
            ;;
        esac
    
    - name: Setup pnpm global directory
      if: inputs.package_manager == 'pnpm'
      shell: bash
      run: |
        echo "Setting up pnpm global directory..."
        export PNPM_HOME="$HOME/.local/share/pnpm"
        export PATH="$PNPM_HOME:$PATH"
        echo "PNPM_HOME=$PNPM_HOME" >> $GITHUB_ENV
        echo "$PNPM_HOME" >> $GITHUB_PATH
        pnpm setup
    
    - name: Install TypeScript globally
      shell: bash
      run: |
        echo "Installing TypeScript globally..."
        case "${{ inputs.package_manager }}" in
          bun)
            bun install -g typescript
            ;;
          yarn)
            yarn global add typescript
            ;;
          pnpm)
            # Ensure PNPM_HOME is in PATH for this step
            export PNPM_HOME="${PNPM_HOME:-$HOME/.local/share/pnpm}"
            export PATH="$PNPM_HOME:$PATH"
            pnpm add -g typescript
            ;;
          npm)
            npm install -g typescript
            ;;
        esac
        tsc --version || { echo "Error: TypeScript not found in PATH"; exit 1; }
    
    - name: Install dependencies
      if: inputs.install_deps == 'true'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if [[ "${{ inputs.allow_lockfile_modifications }}" == "false" ]]; then
          case "${{ inputs.package_manager }}" in
            yarn)
              # For Yarn, use --immutable to prevent any lockfile changes
              ${{ steps.set-pm.outputs.pm }} install --immutable || ${{ steps.set-pm.outputs.pm }} install --frozen-lockfile
              ;;
            pnpm)
              ${{ steps.set-pm.outputs.pm }} install --frozen-lockfile
              ;;
            bun)
              ${{ steps.set-pm.outputs.pm }} install --frozen-lockfile
              ;;
            *)
              # npm - use ci command if package-lock.json exists
              if [[ -f "package-lock.json" ]]; then
                ${{ steps.set-pm.outputs.pm }} ci
              else
                echo "Warning: No package-lock.json found, using regular install"
                ${{ steps.set-pm.outputs.pm }} install
              fi
              ;;
          esac
        else
          # Allow modifications - normal install
          ${{ steps.set-pm.outputs.pm }} install
        fi
    
    - name: Initialize environment
      if: inputs.autoinit_env == 'true'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        ${{ steps.set-pm.outputs.pm_run }} env:init:ci