name: 'Setup Node.js Environment'
description: 'Setup Node.js with mise and package manager (npm, yarn, pnpm, or bun) and install dependencies. Installs all tools defined in mise.toml or .mise.toml'
branding:
  icon: 'package'
  color: 'green'
inputs:
  package_manager:
    description: 'Package manager to use (npm, yarn, pnpm, or bun). Will auto-detect from lockfile if set to "auto"'
    required: false
    default: 'auto'
  install_deps:
    description: 'Install dependencies after setup'
    required: false
    default: 'true'
  working_directory:
    description: 'Working directory for package operations'
    required: false
    default: '.'
  cache_dependencies:
    description: 'Cache dependencies'
    required: false
    default: 'true'
  autoinit_env:
    description: 'Run env:init:ci script after installing dependencies'
    required: false
    default: 'false'
  allow_lockfile_modifications:
    description: 'Allow package managers to create or modify lockfiles'
    required: false
    default: 'true'

outputs:
  pm:
    description: 'Package manager command'
    value: ${{ steps.set-pm.outputs.pm }}
  pm_run:
    description: 'Package manager run command'
    value: ${{ steps.set-pm.outputs.pm_run }}
  cache_hit:
    description: 'Whether the cache was hit'
    value: ${{ steps.cache.outputs.cache-hit }}

runs:
  using: "composite"
  steps:
    - name: Install mise
      uses: jdx/mise-action@v3

    - name: Install tools from mise configuration
      shell: bash
      run: |
        # Check if mise.toml or .mise.toml exists
        if [[ -f "mise.toml" ]] || [[ -f ".mise.toml" ]]; then
          echo "Found mise configuration file, installing all tools..."
          mise install
        else
          echo "Error: No mise.toml or .mise.toml found in the repository"
          echo "Please create a mise.toml file with your required tools"
          echo "Example:"
          echo ""
          echo "[node]"
          echo "version = \"22\""
          echo ""
          echo "[pnpm]"
          echo "version = \"latest\""
          exit 1
        fi

    - name: Detect and set package manager
      id: set-pm
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        PM="${{ inputs.package_manager }}"

        # Auto-detect package manager from lockfile if set to 'auto'
        if [[ "$PM" == "auto" ]]; then
          if [[ -f "bun.lockb" ]]; then
            PM="bun"
            echo "Detected bun from lockfile"
          elif [[ -f "pnpm-lock.yaml" ]]; then
            PM="pnpm"
            echo "Detected pnpm from lockfile"
          elif [[ -f "yarn.lock" ]]; then
            PM="yarn"
            echo "Detected yarn from lockfile"
          elif [[ -f "package-lock.json" ]]; then
            PM="npm"
            echo "Detected npm from lockfile"
          else
            PM="npm"
            echo "No lockfile found, defaulting to npm"
          fi
        fi

        # Set output variables based on detected/specified package manager
        case "$PM" in
          bun)
            echo "pm=bun" >> $GITHUB_OUTPUT
            echo "pm_run=bun run" >> $GITHUB_OUTPUT
            ;;
          yarn)
            echo "pm=yarn" >> $GITHUB_OUTPUT
            echo "pm_run=yarn run" >> $GITHUB_OUTPUT
            ;;
          pnpm)
            echo "pm=pnpm" >> $GITHUB_OUTPUT
            echo "pm_run=pnpm run" >> $GITHUB_OUTPUT
            ;;
          *)
            echo "pm=npm" >> $GITHUB_OUTPUT
            echo "pm_run=npm run" >> $GITHUB_OUTPUT
            ;;
        esac

        echo "Using package manager: $PM"

    - name: Verify package manager installation
      shell: bash
      run: |
        PM="${{ steps.set-pm.outputs.pm }}"
        echo "Verifying $PM installation..."

        # Check if the package manager is available
        if ! command -v "$PM" &> /dev/null; then
          echo "Warning: $PM not found in PATH"
          echo "Available tools from mise:"
          mise list
          echo ""
          echo "Tip: Add $PM to your mise.toml or .mise.toml file to install it automatically"
          echo "Example:"
          echo "  [$PM]"
          echo "  version = 'latest'"
          exit 1
        fi

        $PM --version
        echo "$PM is ready"
    
    - name: Install dependencies
      if: inputs.install_deps == 'true'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        if [[ "${{ inputs.allow_lockfile_modifications }}" == "false" ]]; then
          case "${{ inputs.package_manager }}" in
            yarn)
              # For Yarn, use --immutable to prevent any lockfile changes
              ${{ steps.set-pm.outputs.pm }} install --immutable || ${{ steps.set-pm.outputs.pm }} install --frozen-lockfile
              ;;
            pnpm)
              ${{ steps.set-pm.outputs.pm }} install --frozen-lockfile
              ;;
            bun)
              ${{ steps.set-pm.outputs.pm }} install --frozen-lockfile
              ;;
            *)
              # npm - use ci command if package-lock.json exists
              if [[ -f "package-lock.json" ]]; then
                ${{ steps.set-pm.outputs.pm }} ci
              else
                echo "Warning: No package-lock.json found, using regular install"
                ${{ steps.set-pm.outputs.pm }} install
              fi
              ;;
          esac
        else
          # Allow modifications - normal install
          ${{ steps.set-pm.outputs.pm }} install
        fi
    
    - name: Initialize environment
      if: inputs.autoinit_env == 'true'
      shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        ${{ steps.set-pm.outputs.pm_run }} env:init:ci