name: 'Setup Ubuntu Packages'
description: 'Configure Ubuntu mirrors and install packages for faster, reliable CI builds'
branding:
  icon: 'download'
  color: 'orange'
inputs:
  enable_mirrors:
    description: 'Enable mirror configuration for faster downloads'
    required: false
    default: 'true'
  mirror_url:
    description: 'Primary mirror URL (e.g., https://mirror.init7.net/ubuntu/)'
    required: false
    default: 'https://mirror.init7.net/ubuntu/'
  backup_mirrors:
    description: 'Backup mirror URLs (comma-separated)'
    required: false
    default: 'https://mirror.math.princeton.edu/pub/ubuntu/,https://ftp.halifax.rwth-aachen.de/ubuntu/,https://mirrors.kernel.org/ubuntu/'
  packages:
    description: 'List of packages to install (YAML list or space-separated string)'
    required: false
    default: |
      - git
      - curl
  extra_packages:
    description: 'Additional packages to install (YAML list or space-separated string)'
    required: false
    default: ''
  update_cache:
    description: 'Run apt-get update before package installation'
    required: false
    default: 'true'
  ubuntu_version:
    description: 'Ubuntu version codename (auto-detected if empty)'
    required: false
    default: ''
  retry_count:
    description: 'Number of retry attempts for package installation'
    required: false
    default: '2'
  cache_timeout:
    description: 'Timeout in seconds for package operations'
    required: false
    default: '120'

outputs:
  mirror_configured:
    description: 'Whether mirrors were configured successfully'
    value: ${{ steps.run-script.outputs.configured }}
  packages_installed:
    description: 'List of successfully installed packages'
    value: ${{ steps.run-script.outputs.installed }}
  ubuntu_codename:
    description: 'Detected Ubuntu codename'
    value: ${{ steps.run-script.outputs.codename }}

runs:
  using: "composite"
  steps:
    - name: Run setup-ubuntu-packages script
      id: run-script
      shell: bash
      env:
        ENABLE_MIRRORS: ${{ inputs.enable_mirrors }}
        MIRROR_URL: ${{ inputs.mirror_url }}
        BACKUP_MIRRORS: ${{ inputs.backup_mirrors }}
        PACKAGES: ${{ inputs.packages }}
        EXTRA_PACKAGES: ${{ inputs.extra_packages }}
        UPDATE_CACHE: ${{ inputs.update_cache }}
        UBUNTU_VERSION: ${{ inputs.ubuntu_version }}
        RETRY_COUNT: ${{ inputs.retry_count }}
        CACHE_TIMEOUT: ${{ inputs.cache_timeout }}
      run: |
        set -euo pipefail
        
        # Debug logging
        echo "=== Setup Ubuntu Packages Action ==="
        echo "GitHub Action Path: ${{ github.action_path }}"
        echo "Current Directory: $(pwd)"
        echo "Action Repository: ${{ github.action_repository }}"
        
        # List directory structure for debugging
        echo ""
        echo "=== Directory Structure ==="
        ls -la "${{ github.action_path }}" || echo "Failed to list action path"
        
        # Normalize package lists to space-separated strings
        # Remove YAML list markers (-) and convert newlines to spaces
        export PACKAGES="$(echo "${PACKAGES}" | sed 's/^[[:space:]]*-[[:space:]]*//' | tr '\n' ' ')"
        export EXTRA_PACKAGES="$(echo "${EXTRA_PACKAGES}" | sed 's/^[[:space:]]*-[[:space:]]*//' | tr '\n' ' ')"
        
        echo ""
        echo "=== Package Configuration ==="
        echo "Packages: ${PACKAGES}"
        echo "Extra Packages: ${EXTRA_PACKAGES}"
        
        echo ""
        echo "=== Downloading setup-ubuntu-packages.sh from GitHub ==="
        
        # Download the script directly from GitHub
        # This bypasses the subdirectory action limitation
        TEMP_SCRIPT="/tmp/setup-ubuntu-packages-$$.sh"
        
        # Determine the ref to use (default to v1 if not specified)
        ACTION_REF="${{ github.action_ref }}"
        if [ -z "$ACTION_REF" ]; then
          ACTION_REF="v1"
        fi
        
        echo "Downloading script from ref: $ACTION_REF"
        
        # Download the script using curl or wget
        SCRIPT_URL="https://raw.githubusercontent.com/zondax/actions/$ACTION_REF/setup-ubuntu-packages/setup-ubuntu-packages.sh"
        echo "URL: $SCRIPT_URL"
        
        if command -v curl >/dev/null 2>&1; then
          echo "Using curl to download..."
          curl -sSL "$SCRIPT_URL" -o "$TEMP_SCRIPT" || {
            echo "ERROR: Failed to download script from $SCRIPT_URL"
            echo "HTTP response:"
            curl -sI "$SCRIPT_URL"
            exit 1
          }
        elif command -v wget >/dev/null 2>&1; then
          echo "Using wget to download..."
          wget -q "$SCRIPT_URL" -O "$TEMP_SCRIPT" || {
            echo "ERROR: Failed to download script from $SCRIPT_URL"
            exit 1
          }
        else
          echo "ERROR: Neither curl nor wget is available"
          exit 1
        fi
        
        # Verify the script was downloaded
        if [ ! -f "$TEMP_SCRIPT" ] || [ ! -s "$TEMP_SCRIPT" ]; then
          echo "ERROR: Script download failed or file is empty"
          exit 1
        fi
        
        echo "Script downloaded successfully to: $TEMP_SCRIPT"
        echo "File size: $(stat -c%s "$TEMP_SCRIPT" 2>/dev/null || stat -f%z "$TEMP_SCRIPT" 2>/dev/null || echo "unknown") bytes"
        
        # Make script executable
        chmod +x "$TEMP_SCRIPT"
        
        # Run the script
        echo ""
        echo "=== Executing Script ==="
        "$TEMP_SCRIPT"
        
        # Cleanup
        rm -f "$TEMP_SCRIPT"